<a href="https://colab.research.google.com/github/atharva9699/pythontasks/blob/main/numpy1April.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
a=np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
np.random.random(5)  # 5 random numbers from a standard normal distribution



array([0.24848068, 0.39931235, 0.71526188, 0.70843151, 0.07791903])

In [ ]:
np.random.randint(1, 10)  # Random integer from 1 to 9


7

In [ ]:
np.random.random(5)

array([0.1511984 , 0.82560041, 0.70075688, 0.5517572 , 0.77566757])

In [ ]:
a.itemsize

8

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Dot Product:", np.dot(a, b))


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10)  # Adds 10 to every element


[[11 12 13]
 [14 15 16]]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
indices = np.where(arr > 3)  # Find indices where elements > 3

print("Indices where arr > 3:", indices)
print("Elements:", arr[indices])


Indices where arr > 3: (array([3, 4, 5]),)
Elements: [4 5 6]
